### PR TITLE
CI test

### PR DESCRIPTION
**Pull request by xuxinx**

### CODE REVIEW

**Comment by idealhack** [comment]
I ran the script locally and it seems some cases failed, but I think the script is good.

@xuxinx do you want to fix them before we merge this?

```
ok  	github.com/qor5/admin/activity	0.248s
?   	github.com/qor5/admin/example	[no test files]
?   	github.com/qor5/admin/example/admin	[no test files]
?   	github.com/qor5/admin/example/cmd/publisher	[no test files]
?   	github.com/qor5/admin/example/models	[no test files]
?   	github.com/qor5/admin/example/pages	[no test files]
?   	github.com/qor5/admin/gorm2op	[no test files]
?   	github.com/qor5/admin/l10n	[no test files]
?   	github.com/qor5/admin/l10n/views	[no test files]
?   	github.com/qor5/admin/login	[no test files]
?   	github.com/qor5/admin/media	[no test files]
?   	github.com/qor5/admin/media/filesystem	[no test files]
ok  	github.com/qor5/admin/media/integration	0.219s
?   	github.com/qor5/admin/media/media_library	[no test files]
?   	github.com/qor5/admin/media/oss	[no test files]
?   	github.com/qor5/admin/media/views	[no test files]
# pkg-config --cflags  -- vips vips vips vips
Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
pkg-config: exit status 1
ok  	github.com/qor5/admin/pagebuilder	0.189s
ok  	github.com/qor5/admin/pagebuilder/example	0.345s
ok  	github.com/qor5/admin/presets	0.176s

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.038ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="customers"

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.090ms] [rows:1] SELECT sql FROM sqlite_master WHERE type IN ("table","index") AND tbl_name = "customers" AND sql IS NOT NULL order by type = "table" desc

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.028ms] [rows:-] SELECT * FROM `customers` LIMIT 1

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.016ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="notes"

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.056ms] [rows:1] SELECT sql FROM sqlite_master WHERE type IN ("table","index") AND tbl_name = "notes" AND sql IS NOT NULL order by type = "table" desc

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.018ms] [rows:-] SELECT * FROM `notes` LIMIT 1

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.015ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="credit_cards"

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.054ms] [rows:1] SELECT sql FROM sqlite_master WHERE type IN ("table","index") AND tbl_name = "credit_cards" AND sql IS NOT NULL order by type = "table" desc

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.015ms] [rows:-] SELECT * FROM `credit_cards` LIMIT 1

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.015ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="payments"

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.048ms] [rows:1] SELECT sql FROM sqlite_master WHERE type IN ("table","index") AND tbl_name = "payments" AND sql IS NOT NULL order by type = "table" desc

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.016ms] [rows:-] SELECT * FROM `payments` LIMIT 1

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.014ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="events"

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.049ms] [rows:1] SELECT sql FROM sqlite_master WHERE type IN ("table","index") AND tbl_name = "events" AND sql IS NOT NULL order by type = "table" desc

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.014ms] [rows:-] SELECT * FROM `events` LIMIT 1

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.018ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="companies"

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.069ms] [rows:1] SELECT sql FROM sqlite_master WHERE type IN ("table","index") AND tbl_name = "companies" AND sql IS NOT NULL order by type = "table" desc

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.014ms] [rows:-] SELECT * FROM `companies` LIMIT 1

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.015ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="products"

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.052ms] [rows:1] SELECT sql FROM sqlite_master WHERE type IN ("table","index") AND tbl_name = "products" AND sql IS NOT NULL order by type = "table" desc

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.017ms] [rows:-] SELECT * FROM `products` LIMIT 1

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.014ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="languages"

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.055ms] [rows:1] SELECT sql FROM sqlite_master WHERE type IN ("table","index") AND tbl_name = "languages" AND sql IS NOT NULL order by type = "table" desc

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:112
[0.013ms] [rows:-] SELECT * FROM `languages` LIMIT 1
2023-01-06T14:43:18.645+0900	INFO	presets/presets.go:1109	initializing mux for	{"models": ["products","my_customers","companies","notes","events","credit-cards","languages"], "prefix": "/admin"}
2023/01/06 14:43:18 mounted url /admin/assets/main.js
2023/01/06 14:43:18 mounted url /admin/assets/vue.js
2023/01/06 14:43:18 mounted url /admin/assets/main.css
2023/01/06 14:43:18 mounted url /admin/products
2023/01/06 14:43:18 mounted url /admin/my_customers
2023/01/06 14:43:18 mounted url /admin/my_customers/:id
2023/01/06 14:43:18 mounted url /admin/companies
2023/01/06 14:43:18 mounted url /admin/notes
2023/01/06 14:43:18 mounted url /admin/events
2023/01/06 14:43:18 mounted url /admin/credit-cards
2023/01/06 14:43:18 mounted url /admin/languages

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/gorm2op/operator.go:93
[0.239ms] [rows:1] SELECT * FROM `customers` WHERE id =  "11" ORDER BY `customers`.`id` LIMIT 1

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/gorm2op/operator.go:109
[1.044ms] [rows:1] UPDATE `customers` SET `name`="Felix11",`email`="",`description`="",`company_id`=0,`created_at`="0000-00-00 00:00:00",`updated_at`="2023-01-06 14:43:18.651",`approved_at`=NULL,`term_agreed_at`=NULL,`approval_comment`="",`language_code`="" WHERE id =  "11" AND `id` = 11

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/integration/example_test.go:57
[0.105ms] [rows:1] SELECT * FROM `customers` WHERE `customers`.`id` = 11

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/gorm2op/operator.go:106
[0.888ms] [rows:1] INSERT INTO `customers` (`name`,`email`,`description`,`company_id`,`created_at`,`updated_at`,`approved_at`,`term_agreed_at`,`approval_comment`,`language_code`) VALUES ("Felix","","",0,"2023-01-06 14:43:18.653","2023-01-06 14:43:18.653",NULL,NULL,"","") RETURNING `id`

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/integration/example_test.go:83
[0.104ms] [rows:1] SELECT * FROM `customers` ORDER BY `customers`.`id` LIMIT 1

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/gorm2op/operator.go:106
[0.850ms] [rows:1] INSERT INTO `credit_cards` (`customer_id`,`number`,`expire_year_month`,`name`,`type`,`phone`,`email`) VALUES (11,"12345678","","","","","") RETURNING `id`

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/integration/example_test.go:126
[0.087ms] [rows:1] SELECT * FROM `credit_cards` ORDER BY `credit_cards`.`id` LIMIT 1

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/gorm2op/operator.go:93
[0.117ms] [rows:1] SELECT * FROM `products` WHERE id =  "12" ORDER BY `products`.`id` LIMIT 1

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/gorm2op/operator.go:93
[0.090ms] [rows:1] SELECT * FROM `products` WHERE id =  "12" ORDER BY `products`.`id` LIMIT 1

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/gorm2op/operator.go:109
[0.713ms] [rows:1] UPDATE `products` SET `name`="",`owner_name`="owner1" WHERE id =  "12" AND `id` = 12

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/integration/example_test.go:170
[0.067ms] [rows:1] SELECT * FROM `products` ORDER BY `products`.`id` LIMIT 1

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/examples/setup.go:524
[0.722ms] [rows:1] UPDATE `customers` SET `term_agreed_at`="2023-01-06 14:43:18.666",`updated_at`="2023-01-06 14:43:18.666" WHERE id = "11"

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/integration/example_test.go:218
[0.105ms] [rows:1] SELECT * FROM `customers` ORDER BY `customers`.`id` LIMIT 1
--- FAIL: TestFields (0.00s)
    --- FAIL: TestFields/Read_for_a_time_field (0.00s)
        fields_test.go:176: Read for a time field --- Expected
            +++ Actual
            @@ -1,5 +1,5 @@

            -<td>2019-08-29 11:09:29</td>
            +<td>2019-08-29 12:09:29</td>

             <td>2</td>



2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/integration/gorm_operator_test.go:40
[0.021ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="test_variants"

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/integration/gorm_operator_test.go:40
[0.080ms] [rows:1] SELECT sql FROM sqlite_master WHERE type IN ("table","index") AND tbl_name = "test_variants" AND sql IS NOT NULL order by type = "table" desc

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/integration/gorm_operator_test.go:40
[0.016ms] [rows:-] SELECT * FROM `test_variants` LIMIT 1

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/gorm2op/operator.go:106
[0.786ms] [rows:1] INSERT INTO `test_variants` (`product_code`,`color_code`,`name`) VALUES ("P01","C01","Product 1")

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/gorm2op/operator.go:109
[0.654ms] [rows:1] UPDATE `test_variants` SET `product_code`="P01",`color_code`="C01",`name`="Product 2" WHERE product_code = "P01" AND color_code = "C01"

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/gorm2op/operator.go:93
[0.075ms] [rows:1] SELECT * FROM `test_variants` WHERE product_code = "P01" AND color_code = "C01" ORDER BY `test_variants`.`product_code` LIMIT 1

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/gorm2op/operator.go:114
[0.637ms] [rows:1] DELETE FROM `test_variants` WHERE product_code = "P01" AND color_code = "C01"

2023/01/06 14:43:18 /Users/idealhack/work/qor5/admin/presets/gorm2op/operator.go:93 record not found
[0.066ms] [rows:0] SELECT * FROM `test_variants` WHERE product_code = "P01" AND color_code = "C01" ORDER BY `test_variants`.`product_code` LIMIT 1
FAIL
FAIL	github.com/qor5/admin/presets/integration	0.227s
ok  	github.com/qor5/admin/publish	0.206s
ok  	github.com/qor5/admin/seo	0.231s
ok  	github.com/qor5/admin/slug	0.154s
```

**Review by idealhack — APPROVED** [review]

**Comment by xuxinx** [comment]
```
--- FAIL: TestFields (0.00s)
    --- FAIL: TestFields/Read_for_a_time_field (0.00s)
        fields_test.go:176: Read for a time field --- Expected
            +++ Actual
            @@ -1,5 +1,5 @@

            -<td>2019-08-29 11:09:29</td>
            +<td>2019-08-29 12:09:29</td>

             <td>2</td>
```
let me fix this first.

```
# pkg-config --cflags  -- vips vips vips vips
Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
pkg-config: exit status 1
```
@idealhack will this fail the ci test?

**Comment by idealhack** [comment]
I wonder if we should update https://github.com/qor5/admin/pull/34/commits/41795fdfaf50ad08d8c9e9ab34e58551fbe6d889#diff-678682767f2477de3e3c546746f8568b9a1942b2c647d32331d7e774b8ff8d9fR28 and use that file instead of this script as another wrapper.

And to answer your question, yes, it will https://github.com/qor5/admin/actions/runs/3853002409/jobs/6565590003

**Comment by idealhack** [comment]
Let's continue at https://github.com/qor5/admin/pull/34 then, could you look at the logs and suggest what to change next?

**Comment by idealhack** [comment]
https://github.com/qor5/admin/blob/main/.github/workflows/go.yml works well and we can continue to improve there.

**Pull request closed without merging**
